-- Initial schema reference migration for Nova Cart.
-- The development app can create this schema automatically with SQLAlchemy.
-- Production deployments should apply migrations before starting the API.
CREATE TABLE users (id INTEGER PRIMARY KEY, role VARCHAR(30) NOT NULL, name VARCHAR(120) NOT NULL, phone VARCHAR(30) NOT NULL UNIQUE, password_hash VARCHAR(300), active BOOLEAN NOT NULL DEFAULT 1, created_at TIMESTAMP);
CREATE TABLE shops (id INTEGER PRIMARY KEY, name VARCHAR(160) NOT NULL, category VARCHAR(60) NOT NULL, address VARCHAR(300) NOT NULL, rating FLOAT NOT NULL DEFAULT 4.5, open BOOLEAN NOT NULL DEFAULT 1, dealer_id INTEGER REFERENCES users(id));
CREATE TABLE products (id INTEGER PRIMARY KEY, shop_id INTEGER NOT NULL REFERENCES shops(id), name VARCHAR(180) NOT NULL, category VARCHAR(60) NOT NULL, description TEXT NOT NULL, price_paise INTEGER NOT NULL, stock INTEGER NOT NULL DEFAULT 0, prescription_required BOOLEAN NOT NULL DEFAULT 0, image_url VARCHAR(500), active BOOLEAN NOT NULL DEFAULT 1);
CREATE TABLE sessions (id INTEGER PRIMARY KEY, token_hash VARCHAR(64) NOT NULL UNIQUE, user_id INTEGER NOT NULL REFERENCES users(id), expires_at TIMESTAMP NOT NULL, created_at TIMESTAMP);
CREATE TABLE cart_items (id INTEGER PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), product_id INTEGER NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL, UNIQUE(user_id, product_id));
CREATE TABLE orders (id INTEGER PRIMARY KEY, order_code VARCHAR(40) NOT NULL UNIQUE, customer_id INTEGER NOT NULL REFERENCES users(id), shop_id INTEGER NOT NULL REFERENCES shops(id), status VARCHAR(40) NOT NULL, subtotal_paise INTEGER NOT NULL, delivery_fee_paise INTEGER NOT NULL DEFAULT 0, total_paise INTEGER NOT NULL, payment_status VARCHAR(30) NOT NULL, payment_provider_ref VARCHAR(120), delivery_partner_id INTEGER REFERENCES users(id), customer_address VARCHAR(400) NOT NULL, created_at TIMESTAMP);
CREATE TABLE order_items (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), product_id INTEGER NOT NULL REFERENCES products(id), name_snapshot VARCHAR(180) NOT NULL, unit_price_paise INTEGER NOT NULL, quantity INTEGER NOT NULL);
CREATE TABLE order_events (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), actor_id INTEGER NOT NULL REFERENCES users(id), previous_status VARCHAR(40), new_status VARCHAR(40) NOT NULL, created_at TIMESTAMP);
CREATE TABLE security_events (id INTEGER PRIMARY KEY, actor_id INTEGER REFERENCES users(id), event_type VARCHAR(80) NOT NULL, detail TEXT NOT NULL, ip VARCHAR(80) NOT NULL, created_at TIMESTAMP);
CREATE TABLE prescriptions (id INTEGER PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), customer_id INTEGER NOT NULL REFERENCES users(id), storage_key VARCHAR(300) NOT NULL, status VARCHAR(30) NOT NULL, ocr_status VARCHAR(30) NOT NULL, created_at TIMESTAMP);
