let user=null, products=[], cart={items:[],total_paise:0}, orders=[], category='All', page='home', toastTimer;
const cats=['All','Medical','Grocery','Milk Products','Stationery','Bakery','Restaurants','Footwear','Accessories','Clothing'];
const $=id=>document.getElementById(id); const money=p=>'₹'+(p/100).toFixed(2);
async function api(path,opt={}){let h=new Headers(opt.headers||{});if(opt.method&&opt.method!=='GET'){const c=document.cookie.split('; ').find(x=>x.startsWith('nova_csrf='));if(c)h.set('X-CSRF-Token',decodeURIComponent(c.split('=')[1]));}const r=await fetch(path,{...opt,headers:h,credentials:'include'});const d=await r.json();if(!r.ok)throw Error(d?.detail?.message||d?.detail||'Request failed');return d}
async function boot(){await fetch('/api/csrf',{credentials:'include'});try{user=await api('/api/me')}catch{}await load();render()}
async function load(){products=await api('/api/catalog?q='+(encodeURIComponent($('search').value||''))+'&category='+(category==='All'?'':encodeURIComponent(category)));try{cart=await api('/api/cart')}catch{}try{orders=await api('/api/orders')}catch{orders=[]}}
function moneyInput(v){return `<input value="${v.replace(/"/g,'&quot;')}"/>`}
function render(){const root=$('app'); if(page==='home')root.innerHTML=home();else if(page==='cart')root.innerHTML=cartView();else if(page==='orders')root.innerHTML=ordersView();else root.innerHTML=roleView(page);$('authBtn').textContent=user?'Sign out':'Sign in';$('workBtn').style.display=user?'inline-block':'none';bind();}
function home(){return `<main class="wrap hero"><div class="ey">LOCAL COMMERCE, REIMAGINED</div><h1>Everything nearby. <span>One cart.</span></h1><p class="muted" style="max-width:720px;font-size:18px;line-height:1.7">Discover local shops, track orders and give independent stores a better digital storefront.</p><div class="chips">${cats.map(c=>`<button class="chip ${category===c?'on':''}" onclick="setCat('${c}')">${c}</button>`).join('')}</div><div class="section"><div><div class="muted">CATALOG</div><h2>Popular near you</h2></div><span class="muted">${products.length} products</span></div><div class="grid">${products.filter(p=>p.stock>0).map(p=>`<article class="card"><div class="pic"><img src="${p.image_url||'/placeholder.svg'}"></div><div class="shop">${p.shop_name} · ★ ${p.shop_rating}</div><h3>${p.name}</h3><p>${p.description}</p><div class="bottom"><b>${money(p.price_paise)}</b><button class="btn primary small" onclick="add(${p.id})">Add</button></div></article>`).join('')}</div></main>`}
function cartView(){if(!cart.items.length)return `<main class="wrap page"><h1>Your cart</h1><div class="panel muted">Your cart is empty. Add a product from the marketplace.</div></main>`;return `<main class="wrap page"><div class="section"><h2>Your cart</h2><span class="muted">${cart.items.length} lines</span></div><div class="panel">${cart.items.map(i=>`<div class="row"><div><b>${i.name}</b><div class="muted">${i.quantity} × ${money(i.price_paise)}</div></div><button class="btn" onclick="removeItem(${i.product_id})">Remove</button></div>`).join('')}<div class="total"><span>Total</span><b>${money(cart.total_paise+(cart.total_paise<49900?4900:0))}</b></div><label class="muted">Delivery address${moneyInput('12 Lake View Road, Vijayawada')}</label><label class="muted">Payment<select id="pay"><option value="COD">Cash on delivery</option><option value="MOCK_UPI">Mock UPI — development only</option></select></label><button class="btn primary" style="width:100%;margin-top:10px" onclick="placeOrder()">Place order</button></div></main>`}
function ordersView(){return `<main class="wrap page"><div class="section"><h2>${user?.role==='CUSTOMER'?'Your orders':'Orders'}</h2></div>${orders.length?orders.map(o=>`<div class="order row"><div><b>${o.order_code}</b><div class="muted">${o.shop} · ${money(o.total_paise)}</div><small class="muted">${new Date(o.created_at).toLocaleString()}</small></div><div><b style="color:#58f0be">${o.status}</b></div></div>`).join(''):`<div class="panel muted">No orders yet.</div>`}</main>`}
function roleView(r){if(!user)return `<main class="wrap page"><div class="panel muted">Sign in to access the ${r} workspace.</div></main>`; if(r==='dealer')return `<main class="wrap page"><div class="ey">DEALER</div><h1>Command Center</h1><p class="muted">Role-scoped order operations backed by the API.</p>${orders.map(o=>`<div class="order row"><div><b>${o.order_code}</b><div class="muted">${o.shop} · ${money(o.total_paise)}</div></div><div>${dealerAction(o)}</div></div>`).join('')}</main>`; if(r==='delivery')return `<main class="wrap page"><div class="ey">DELIVERY PARTNER</div><h1>Delivery Hub</h1><div class="panel muted">Assigned deliveries appear here. Live GPS requires a configured provider and device permissions.</div>${orders.map(o=>`<div class="order row"><div><b>${o.order_code}</b><div class="muted">${o.status}</div></div><div>${deliveryAction(o)}</div></div>`).join('')}</main>`; return `<main class="wrap page"><div class="ey">ADMIN</div><h1>Platform Overview</h1><div id="metrics" class="metric"></div><div class="grid" style="margin-top:20px"><div class="panel"><b>Security</b><p class="muted">HttpOnly sessions, CSRF, hashed passwords, role/object checks, security headers and rate limits.</p></div><div class="panel"><b>Provider readiness</b><p class="muted">Payment, OCR, routing and notifications are explicitly mock/development adapters.</p></div></div></main>`}
function dealerAction(o){const next={PAYMENT_CONFIRMED:'SHOP_SELECTION',SHOP_SELECTION:'SHOP_ACCEPTED',SHOP_ACCEPTED:'PREPARING',PREPARING:'READY_FOR_PICKUP'}[o.status];return next?`<button class="btn primary" onclick="change(${o.id},'${next}')">${next.replaceAll('_',' ')}</button>`:`<span class="muted">${o.status}</span>`}
function deliveryAction(o){const next={DELIVERY_ASSIGNED:'PICKED_UP',PICKED_UP:'OUT_FOR_DELIVERY',OUT_FOR_DELIVERY:'DELIVERED'}[o.status];return next?`<button class="btn primary" onclick="change(${o.id},'${next}')">${next.replaceAll('_',' ')}</button>`:`<span class="muted">${o.status}</span>`}
function go(p){page=p;load().then(render).catch(e=>show(e.message))}function setCat(c){category=c;go('home')}async function add(id){try{if(!user){return loginModal()}cart=await api('/api/cart',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({product_id:id,quantity:1})});show('Added to cart');render()}catch(e){show(e.message)}}async function removeItem(id){cart=await api('/api/cart/'+id,{method:'DELETE'});render()}async function placeOrder(){const address=document.querySelector('.panel label input').value;try{await api('/api/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({address,payment_method:$('pay').value})});show('Order created');await load();go('orders')}catch(e){show(e.message)}}async function change(id,status){try{await api('/api/orders/'+id+'/transition',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});await load();render()}catch(e){show(e.message)}}
function loginModal(){document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="modal"><div class="box"><div class="ey">DEMO ACCESS</div><h2>Sign in to Nova Cart</h2><label>Phone<input id="lp" value="9000000001"></label><label>Password<input id="lpass" type="password" value="customer123"></label><button class="btn primary" style="width:100%" onclick="doLogin()">Sign in</button><p class="muted" style="font-size:12px">Customer 9000000001/customer123 · Dealer 9000000002/dealer123 · Delivery 9000000003/delivery123 · Admin 9000000004/admin123</p></div></div>`)}
async function doLogin(){try{const r=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phone:$('lp').value,password:$('lpass').value})});user=r.user;document.getElementById('modal').remove();await load();render();show('Welcome, '+user.name)}catch(e){show(e.message)}}
$('authBtn').onclick=()=>user?logout():loginModal();$('workBtn').onclick=()=>user&&go(user.role==='CUSTOMER'?'orders':user.role==='DEALER'?'dealer':user.role==='DELIVERY_PARTNER'?'delivery':'admin');$('search').oninput=()=>{clearTimeout(window._s);window._s=setTimeout(()=>go(page),250)};
async function logout(){await api('/api/auth/logout',{method:'POST'});user=null;go('home')}
async function adminLoad(){if(user?.role==='ADMIN'){try{const x=await api('/api/admin/overview');const m=document.querySelector('#metrics');if(m)m.innerHTML=Object.entries(x).map(([k,v])=>`<div><b>${v}</b><small>${k.replaceAll('_',' ')}</small></div>`).join('')}catch{}}}
function bind(){adminLoad()}
function show(t){const b=document.createElement('button');b.className='toast';b.textContent=t;document.body.appendChild(b);setTimeout(()=>b.remove(),2600)}
boot();
